apiVersion: operate-first.cloud/v1
kind: acmClusterGenerator
metadata:
  name: install-config-generator
spec:
  baseDomain: example.com
  clusterName: testcluster
  enableArgoCd: true
  networking:
    machineCIDR: 10.1.0.0/24
    apiVIP: 10.1.0.171
    ingressVIP: 10.1.0.173
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    networkType: OpenShiftSDN
    serviceNetwork:
      - 172.30.0.0/16
  baremetal:
    bmcUsername: user
    bmcPassword: secretpassword
    disableCertificateVerification: true
    hosts:
      - name: os-ctrl-0
        role: master
        bmc:
          address: 'ipmi://10.0.15.5'
        bootMACAddress: 'd4:ae:52:a5:0c:c4'
      - name: os-ctrl-1
        role: master
        bmc:
          address: 'ipmi://10.0.3.5'
        bootMACAddress: 'd4:ae:52:98:22:25'
      - name: os-ctrl-2
        role: master
        bmc:
          address: 'ipmi://10.0.5.7'
        bootMACAddress: '90:e2:ba:ad:89:40'
  provisioning:
    libvirtURI: 'qemu+ssh://root@provisioner.testcluster.example.com/system'
    provisioningNetworkCIDR: 172.22.1.0/24
    provisioningNetworkInterface: eno1
    provisioningBridge: provisioning
    externalBridge: baremetal
    imageSetRef:
      name: img4.7.0-x86-64-appsub
  ssh:
    sshKnownHosts:
      - "provisioner.testcluster.example.com,10.1.0.170 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLvpVKaOfX870TZfbxETKZr0FoW3XaS9WdC/U5OUdwQSCQRyBdXauNgPE2iR1TJsOU0VGSUgrL0+YhIQifolZS8="
    sshPublicKey: >-
      ssh-rsa ...insert public part here...
    sshPrivateKey: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      ...insert secret here...
      -----END OPENSSH PRIVATE KEY-----
  pullSecret: |
    {
      "auths": {
      }
    }
